### ISSUE TITLE
超哥,是不是所有的控制器,只能在handle里面处理逻辑

### ISSUE THREAD

**Issue by uniteweiwei** [overtrue/yaf-skeleton#10]
我新建一个方法,url无论如何都访问不到

![image](https://user-images.githubusercontent.com/19373139/41586513-861494de-73df-11e8-8f4f-82ea1d9fa46e.png)
会把它当做一个PHP文件来执行
![image](https://user-images.githubusercontent.com/19373139/41586541-9e793912-73df-11e8-809c-b62058fc854b.png)

**Comment by uniteweiwei** [comment]
文档我参考的yaf的文档,nginx里面把PATH_INFO屏蔽了

**Comment by overtrue** [comment]
是的

**Comment by uniteweiwei** [comment]
那方法多的话,那不是得很多个.php文件哦...分为不同的目录也感觉太多了...

**Comment by overtrue** [comment]
@uniteweiwei 你可以考虑做一下自定义拓展
