### ISSUE TITLE
Bug及建议

### ISSUE THREAD

**Issue by zuoRambo** [overtrue/yaf-skeleton#12]
下面字符串转ASCII的方法找不到类...

https://github.com/overtrue/yaf-skeleton/blob/bfb5624a1975caa5f50efa32d7c6e547b6c1c4de/app/support/Str.php#L48

建议：
1. 引入EloquentORM，帮助广大群众解决ORM问题
2. 引入一个成熟Validator，解放广大群众于参数校验泥潭

**Comment by overtrue** [comment]
@zuoRambo 嗯，感谢反馈。那个 ASCII 感觉用处不是很大，我先移除了。另外引入 ORM 这个，我觉得在自己使用的时候没问题的，但是内置的话可能并不是所有人想要的，我遇到不少人反感 Laravel 的设计，所以这部分保守的人还是不太喜欢的，就不默认内置了，我可以加到 "suggestions" 中去。
