### ISSUE TITLE
超哥是打算在yaf基础上设计一个如laravel一般好用么？

### ISSUE THREAD

**Issue by domyhero** [overtrue/yaf-skeleton#13]
可以分享下具体的设计思路么？大家一起来完善

**Comment by overtrue** [comment]
因为 Laravel 用惯了，忍受不了这种啥都没有的框架，所以就在上面做了一些基础的封装，目前的程度应该是差不多了，再封装多了就不适合了，大家要自己拓展的话就再加功能就好了。目前的程度适合 API 或者其它 web 也没问题。
