### ISSUE TITLE
Config::set($key, $value)方法没有实现

### ISSUE THREAD

**Issue by idamon** [overtrue/yaf-skeleton#18]
file: app\helpers.php
```php
function config($property, $default = null)
    {
        if (is_array($property)) {
            list($key, $value) = $property;
            /**
             *此处报错， Config 类没有实现该 set 方法
             */
            return Config::set($key, $value);
        }

        return Config::get($property, $default);
    }
```

**Comment by overtrue** [comment]
报错贴一下

**Comment by overtrue** [comment]
https://www.php.net/manual/en/class.yaf-config-abstract

**Comment by idamon** [comment]
> https://www.php.net/manual/en/class.yaf-config-abstract
这里的 Config::set()并不是直接调用 yaf 扩展的内置 Config_Abstract 类， 
而是这个重新封装的 config 类：
[https://github.com/overtrue/yaf-skeleton/blob/master/app/facades/Config.php](url)
这里并没有实现 set 方法
如果config($property) $property 是数组时，就会报错 "Call to undefined method Config::set()"

**Comment by overtrue** [comment]
感谢，已修改
