### ISSUE TITLE
测试用例失败

### ISSUE THREAD

**Issue by caojiabin2012** [overtrue/yaf-skeleton#8]
直接运行测试用例提示：
![image](https://user-images.githubusercontent.com/12596466/40614055-a5efc838-62b3-11e8-81d7-ba4e69925c20.png)
tests/Registry.php
tests/Dispatcher.php
都是同样问题，将namespace由Yaf改成Yaf\Tests 解决此问题，在运行测试用例提示：
![image](https://user-images.githubusercontent.com/12596466/40614150-209d31f6-62b4-11e8-92d4-2379bcaa831f.png)

请指点下错在了哪里，为何运行测试用例不成功，或者能在README.md里增加基本测试通过的运行命令。

**Comment by overtrue** [comment]
@caojiabin2012 Yaf 是以拓展形式安装的，所以无法在安装了该拓展的环境运行单元测试，建议在无 yaf 环境运行测试，我们之前的做法是有一个专门跑测试的 docker 镜像。这个事儿目前没有更好的解决方法。

**Comment by caojiabin2012** [comment]
框架搭建的这么优秀，不能直接运行测试用例，实在是不完美啊！哈哈，多谢超哥指点～

**Comment by overtrue** [comment]
@caojiabin2012 没办法，这是语言层面的东西。
